author: Harbo5
main: dev.harbo.showip.ShowIP
name: ShowIP
version: 1.0.1
api-version: 1.20
commands:
  showip:
    description: Shows a players IP in a title popup
    aliases: [ipshow]
    permission: showip.admin